// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a type for our supabase client that can be null
export type SupabaseClientType = SupabaseClient<Database> | null;

// Check if environment variables are properly set
if (!SUPABASE_URL) {
  console.warn('VITE_SUPABASE_URL is not set. Supabase client will be unavailable.');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.warn('VITE_SUPABASE_PUBLISHABLE_KEY is not set. Supabase client will be unavailable.');
}

// Export the supabase client, or null if environment variables are missing
export const supabase: SupabaseClientType = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY 
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: false, // Prevent URL manipulation
      },
      global: {
        headers: {
          'X-Client-Info': 'trusty-check-app',
        },
      },
      db: {
        schema: 'public',
      },
    })
  : null;